# .goreleaser.yml
project_name: ctl

# .goreleaser.yml
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go get -u github.com/gobuffalo/packr/v2/packr2
    - packr2

archives:
  - files:
    - none*
