Document: ctl
Title: Debian ctl Manual
Author: <insert document author here>
Abstract: This manual describes what ctl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ctl/ctl.sgml.gz

Format: postscript
Files: /usr/share/doc/ctl/ctl.ps.gz

Format: text
Files: /usr/share/doc/ctl/ctl.text.gz

Format: HTML
Index: /usr/share/doc/ctl/html/index.html
Files: /usr/share/doc/ctl/html/*.html
